name: hexlet-ci-app-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - uses: actions/checkout@v4

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Установка проекта (зависимостей)
      - name: Install dependencies
        run: make setup

      # 4. Запуск тестов (и линтера, если он есть в make-командах)
      - name: Run tests
        run: make test

      # 5. Кастомный экшен Хекслета
      - name: Hello from Hexlet Action
        uses: hexlet-components/hello-from-hexlet-action@release
