name: hexlet-ci-app-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Шаг 1: Установка зависимостей и настройка окружения
      - name: Install dependencies
        run: make setup

      # Шаг 2: Проверка стиля кода (линтер)
      - name: Run linter
        run: make lint

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: make test
